
CREATE TABLE LIBROS
(
	ISBN                VARCHAR2(12),
	TITULO              VARCHAR2(100),
	ESTADO              VARCHAR2(7),
	LOCALIZADOR         VARCHAR2(8),
	CONSTRAINT          "PK_LIBROS"                     PRIMARY KEY (ISBN),
	CONSTRAINT 			"UK_LIBROS.LOCALIZADOR"			UNIQUE (LOCALIZADOR),
	CONSTRAINT          "NN_LIBROS.TITULO"              CHECK (TITULO IS NOT NULL),
	CONSTRAINT 			"NN_LIBROS.ESTADO"				CHECK (ESTADO IS NOT NULL),
	CONSTRAINT          "CH_LIBROS.ESTADO"              CHECK (ESTADO IN ('LIBRE', 'OCUPADO'))
)


CREATE TABLE SOCIOS
(
	CODIGO              VARCHAR2(6),
	DNI                 VARCHAR2(12),
	NOMBRE              VARCHAR2(100),
	CONSTRAINT          "PK_SOCIOS"                     PRIMARY KEY (CODIGO),
    CONSTRAINT          "UK_SOCIOS"                     UNIQUE (DNI),
    CONSTRAINT          "NN_SOCIOS.DNI"                 CHECK (DNI IS NOT NULL),
	CONSTRAINT          "NN_SOCIOS.NOMBRE"              CHECK (NOMBRE IS NOT NULL)
)

CREATE TABLE PRESTAMOS 
(
    LOCALIZADOR       VARCHAR2(8),
    ISBN              VARCHAR2(12),
    DNI               VARCHAR2(12),
    FECHA_PRESTAMO    DATE,
    FECHA_DEVOLUCION  DATE,
    CONSTRAINT        "PK_PRESTAMOS"                 PRIMARY KEY (LOCALIZADOR),
    CONSTRAINT        "FK_PRESTAMOS.ISBN"            FOREIGN KEY (ISBN)
                                                     REFERENCES LIBROS(ISBN),
    CONSTRAINT        "FK_PRESTAMOS.DNI"             FOREIGN KEY (DNI)
                                                     REFERENCES SOCIOS(DNI),  
    CONSTRAINT        "NN_PRESTAMOS.ISBN"            CHECK (ISBN IS NOT NULL),
    CONSTRAINT        "NN_PRESTAMOS.DNI"             CHECK (DNI IS NOT NULL),
    CONSTRAINT        "NN_PRESTAMOS.FECHA_PRESTAMO"  CHECK (FECHA_PRESTAMO IS NOT NULL)
)


ALTER TABLE LIBROS
 ADD CONSTRAINT "FK_LIBROS.LOCALIZADOR"	FOREIGN KEY (LOCALIZADOR)
 										REFERENCES PRESTAMOS(LOCALIZADOR)
ALTER TABLE PRESTAMOS
    ADD CONSTRAINT "DF_PRESTAMOS.FECHA_DEVOLUCION"
    DEFAULT ('PRESTADO') FOR FECHA_DEVOLUCION

CREATE SEQUENCE SEQ_SOCIOS
	MINVALUE 1
	MAXVALUE 999998
	START WITH 1
	INCREMENT BY 1

CREATE SEQUENCE SEQ_PRESTAMOS
	MINVALUE 1
	MAXVALUE 99999998
	START WITH 1
	INCREMENT BY 1

 